# Generated by Django 5.0.7 on 2024-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_booking_appointment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
